export const CONTACT_US_SUCCESS_MSG = 'Thank You for your Message!'
export const ERROR_ALL_FIELD_REQUIRED = 'Error: all fields are required'
export const ERROR_INVALID_EMAIL = 'Error: Invalid email address'
export const IFRAME_PAGE_HEADER = 'WebdriverUniversity.com (IFrame)'
export const IFRAME_POPUP_DIALOG_TITLE = 'Welcome to webdriveruniversity.com'
export const POPUP_ALERT_PAGE_HEADER = 'Annoying Popup & Alerts!'
export const POPUP_ALERT_MODEL_WINDOW_HEADER = 'It’s that Easy!! Well I think it is.....'
export const POPUP_ALERT_TEXT = 'Press a button!'